# Generated by Django 2.1.5 on 2019-12-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SharkTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('deal', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=100)),
                ('equity', models.CharField(max_length=20)),
                ('valuation', models.CharField(max_length=50)),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='st_app1.Episode')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='st_app1.Season')),
            ],
        ),
    ]
