# Generated by Django 2.1.5 on 2019-12-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharkTank',
            new_name='Company',
        ),
    ]
