# Generated by Django 2.1.5 on 2019-12-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0004_auto_20191210_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='st_app1.Company'),
        ),
    ]
