# Generated by Django 2.1.5 on 2019-12-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0005_auto_20191218_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='st_app1.Company'),
        ),
    ]
