# Generated by Django 2.1.5 on 2019-12-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0007_auto_20191218_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
