# Generated by Django 2.1.5 on 2019-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0010_episode_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ManyToManyField(null=True, related_name='etb_season', to='st_app1.Season'),
        ),
    ]
