# Generated by Django 2.1.5 on 2019-12-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0012_auto_20191219_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='season',
        ),
        migrations.AddField(
            model_name='company',
            name='showlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showlist', to='st_app1.Episode'),
        ),
    ]
