# Generated by Django 2.1.5 on 2019-12-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app1', '0013_auto_20191219_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.AddField(
            model_name='product',
            name='showlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_showlist', to='st_app1.Episode'),
        ),
    ]
